#include "emit.h"

#include <cctype>
#include <set>
#include <sstream>

#include "checks.h"
#include "prims.h"

namespace rg {

namespace {

// Hands out identifiers. With fixing on: illegal characters become '_',
// keywords get "_r", clashes get "_2", "_3"... in the order names are
// claimed, which is the description's order, so output is reproducible.
class Names {
 public:
  explicit Names(bool fix) : fix_(fix) {}

  void reserve(const std::string& n) { taken_.insert(n); }

  std::string claim(const std::string& want) {
    if (!fix_) {
      taken_.insert(want);
      return want;
    }
    std::string s;
    for (char c : want) s += (std::isalnum((unsigned char)c) || c == '_') ? c : '_';
    if (s.empty() || std::isdigit((unsigned char)s[0])) s = "n_" + s;
    if (is_verilog_keyword(s)) s += "_r";
    std::string n = s;
    for (int k = 2; taken_.count(n); k++) n = s + "_" + std::to_string(k);
    taken_.insert(n);
    return n;
  }

 private:
  bool fix_;
  std::set<std::string> taken_;
};

std::string range(long w, const std::string& wtext) {
  if (w == 1) return "";
  if (w > 1) return "[" + std::to_string(w - 1) + ":0] ";
  return "[(" + wtext + ")-1:0] ";  // couldn't evaluate; leave it to the tool
}

class Emitter {
 public:
  Emitter(Netlist& nl, bool fix) : nl_(nl), fix_(fix), modnames_(fix) {}

  std::string run(const std::string& source) {
    for (const auto& p : all_prims()) modnames_.reserve(p.name);
    for (const auto& m : nl_.mods) {
      std::string n = modnames_.claim(m.name);
      if (n != m.name) renamed(m.name, "module", m.name, n);
      modname_[m.name] = n;
    }

    std::ostringstream body;
    for (const auto& m : nl_.mods) body << module(m) << "\n";

    std::ostringstream out;
    out << "// Generated by rtlgen from " << source << ". Do not edit by hand.\n";
    out << "// top: " << (modname_.count(nl_.top) ? modname_[nl_.top] : nl_.top) << ", " << nl_.mods.size()
        << " module(s)\n\n";
    for (const auto& p : all_prims())
      if (used_prims_.count(p.name)) out << p.verilog << "\n";
    // generated code declares every net; make a typo an error instead of an implicit wire
    out << "`default_nettype none\n\n" << body.str() << "`default_nettype wire\n";
    return out.str();
  }

 private:
  void renamed(const std::string& mod, const std::string& what, const std::string& from, const std::string& to) {
    nl_.diags.push_back({"W_RENAMED", false, mod, what + " " + from, "'" + from + "' emitted as '" + to + "'"});
  }

  struct Wire {
    std::string name;
    long width;
    std::string wtext;
  };

  std::string module(const Module& m) {
    Names names(fix_);
    for (const auto& p : m.ports) names.reserve(p.name);

    std::vector<std::string> iname(m.insts.size());
    for (size_t i = 0; i < m.insts.size(); i++) {
      iname[i] = names.claim(m.insts[i].name);
      if (iname[i] != m.insts[i].name) renamed(m.name, "instance", m.insts[i].name, iname[i]);
    }

    // one wire per instance output
    std::vector<Wire> wires;
    std::map<std::pair<int, std::string>, std::string> out_wire;
    for (size_t i = 0; i < m.insts.size(); i++)
      for (const auto& p : m.insts[i].ports)
        if (p.out) {
          std::string want = m.insts[i].name + "_" + p.name;
          std::string n = names.claim(want);
          if (n != want) renamed(m.name, "wire", want, n);
          out_wire[{(int)i, p.name}] = n;
          wires.push_back({n, p.width, p.wtext});
        }

    auto port_width = [&](const Ep& e) -> std::pair<long, std::string> {
      if (e.inst == -1) {
        if (const Port* p = m.port(e.port)) return {p->width, p->wtext};
      } else if (e.inst >= 0) {
        for (const auto& p : m.insts[e.inst].ports)
          if (p.name == e.port) return {p.width, p.wtext};
      }
      return {1, "1"};
    };
    auto base_name = [&](const Ep& e) -> std::string {
      if (e.inst == -1) return e.port;
      auto it = out_wire.find({e.inst, e.port});
      if (it != out_wire.end()) return it->second;
      // only reachable without checks (driving from an input, unknown port...)
      std::string in = e.inst >= 0 ? m.insts[e.inst].name : e.text.substr(0, e.text.find('.'));
      return in + "_" + e.port;
    };

    std::vector<std::string> inst_lines, assigns;
    std::map<std::pair<int, std::string>, std::vector<std::string>> load_exprs;

    for (const auto& c : m.conns) {
      auto [lw, lwt] = port_width(c.to);
      auto [fw, fwt] = port_width(c.from);
      std::string base = base_name(c.from);
      long lo = c.from.sliced() && c.from.lo >= 0 ? c.from.lo : 0;
      long dw = c.from.sliced() && c.from.hi >= c.from.lo ? c.from.hi - c.from.lo + 1 : fw;
      bool whole = !c.from.sliced();
      auto bits = [&](long hi, long l) {
        if (whole && l == 0 && hi == fw - 1) return base;
        return hi == l ? base + "[" + std::to_string(hi) + "]" : base + "[" + std::to_string(hi) + ":" + std::to_string(l) + "]";
      };
      std::string e = c.from.sliced() ? bits(c.from.hi, c.from.lo) : base;
      if (c.adapt == Adapt::Trunc && lw > 0) e = bits(lo + lw - 1, lo);
      if (c.invert) e = "~" + e;
      if ((c.adapt == Adapt::Zext || c.adapt == Adapt::Sext) && lw > dw && dw > 0) {
        std::string fill = "1'b0";
        if (c.adapt == Adapt::Sext) fill = (c.invert ? "~" : "") + bits(lo + dw - 1, lo + dw - 1);
        e = "{{" + std::to_string(lw - dw) + "{" + fill + "}}, " + e + "}";
      }
      if (c.pipeline > 0) {
        std::string clk, rst;
        for (const auto& p : m.ports) {
          if (!p.out && p.kind == Kind::Clock && clk.empty()) clk = p.name;
          if (!p.out && p.kind == Kind::Reset && rst.empty()) rst = p.name;
        }
        std::string load = c.to.inst >= 0 ? m.insts[c.to.inst].name + "_" + c.to.port : c.to.port;
        std::string pin = names.claim(load + "_pipe");
        std::string pq = names.claim(load + "_pipe_q");
        wires.push_back({pq, lw, lwt});
        used_prims_.insert("rg_pipe");
        inst_lines.push_back("  rg_pipe #(.WIDTH(" + (lw > 0 ? std::to_string(lw) : lwt) + "), .STAGES(" +
                             std::to_string(c.pipeline) + ")) " + pin + " (.clk(" + clk + "), .rst_n(" + rst +
                             "), .d(" + e + "), .q(" + pq + "));");
        e = pq;
      }
      load_exprs[{c.to.inst, c.to.port}].push_back(e);
    }
    for (const auto& t : m.ties) {
      auto [lw, lwt] = port_width(t.to);
      load_exprs[{t.to.inst, t.to.port}].push_back(lw > 0 ? std::to_string(lw) + "'d" + std::to_string(t.value)
                                                          : std::to_string(t.value));
    }

    // instance inputs: one expression, or (only without checks) a shared
    // wire that every driver assigns to
    auto input_expr = [&](int inst, const std::string& port, long w, const std::string& wt) -> std::string {
      auto it = load_exprs.find({inst, port});
      if (it == load_exprs.end() || it->second.empty()) return "";
      if (it->second.size() == 1) return it->second[0];
      std::string n = names.claim(m.insts[inst].name + "_" + port + "_in");
      wires.push_back({n, w, wt});
      for (const auto& e : it->second) assigns.push_back("  assign " + n + " = " + e + ";");
      return n;
    };

    for (size_t i = 0; i < m.insts.size(); i++) {
      const Inst& in = m.insts[i];
      std::string type = in.prim ? in.type : (modname_.count(in.sub) ? modname_[in.sub] : in.type);
      if (in.prim) used_prims_.insert(in.type);
      std::ostringstream os;
      os << "  " << type;
      if (in.prim && !in.params.empty()) {
        os << " #(";
        bool first = true;
        for (const auto& [k, v] : in.params) {
          os << (first ? "" : ", ") << "." << k << "(" << v << ")";
          first = false;
        }
        os << ")";
      } else if (!in.known && !in.param_text.empty()) {
        os << " #(";
        for (size_t k = 0; k < in.param_text.size(); k++)
          os << (k ? ", " : "") << "." << in.param_text[k].first << "(" << in.param_text[k].second << ")";
        os << ")";
      }
      os << " " << iname[i] << " (";
      std::vector<std::string> pins;
      if (in.known) {
        for (const auto& p : in.ports)
          pins.push_back("." + p.name + "(" +
                         (p.out ? out_wire[{(int)i, p.name}] : input_expr((int)i, p.name, p.width, p.wtext)) + ")");
      } else {
        std::set<std::string> seen;
        for (const auto& c : m.conns)
          for (const Ep* e : {&c.from, &c.to})
            if (e->inst == (int)i && seen.insert(e->port).second)
              pins.push_back("." + e->port + "(" + (e == &c.to ? input_expr((int)i, e->port, 1, "1") : base_name(*e)) + ")");
      }
      for (size_t k = 0; k < pins.size(); k++) os << (k ? ", " : "") << pins[k];
      os << ");";
      inst_lines.push_back(os.str());
    }

    for (const auto& p : m.ports) {
      if (!p.out) continue;
      auto it = load_exprs.find({-1, p.name});
      if (it == load_exprs.end()) continue;
      for (const auto& e : it->second) assigns.push_back("  assign " + p.name + " = " + e + ";");
    }

    std::ostringstream os;
    os << "module " << modname_[m.name] << " (";
    for (size_t k = 0; k < m.ports.size(); k++) {
      const Port& p = m.ports[k];
      os << (k ? "," : "") << "\n  " << (p.out ? "output wire " : "input wire ") << range(p.width, p.wtext) << p.name;
    }
    os << "\n);\n";
    for (const auto& w : wires) os << "  wire " << range(w.width, w.wtext) << w.name << ";\n";
    if (!wires.empty()) os << "\n";
    for (const auto& l : inst_lines) os << l << "\n";
    if (!assigns.empty()) os << "\n";
    for (const auto& a : assigns) os << a << "\n";
    os << "endmodule\n";
    return os.str();
  }

  Netlist& nl_;
  bool fix_;
  Names modnames_;
  std::map<std::string, std::string> modname_;
  std::set<std::string> used_prims_;
};

}  // namespace

std::string emit_verilog(Netlist& nl, bool fix_names, const std::string& source) {
  return Emitter(nl, fix_names).run(source);
}

}  // namespace rg
